### ISSUE TITLE
Consider using the mount module rather than running 'mount'

### ISSUE THREAD

**Issue by rvasilev** [linux-noob/hcloud-k8s#3]
https://github.com/linux-noob/hcloud-k8s/blob/b40b49ba2977209377b9734a40db272192762119/roles/kube-prepare/tasks/main.yaml#L53

https://docs.ansible.com/ansible/latest/modules/mount_module.html#examples
```
- name: Mount up device by label
  mount:
    path: /srv/disk
    src: LABEL=SOME_LABEL
    fstype: ext4
    state: present

- name: Mount up device by UUID
  mount:
    path: /home
    src: UUID=b3e48f45-f933-4c8e-a700-22a159ec9077
    fstype: xfs
    opts: noatime
    state: present

- name: Unmount a mounted volume
  mount:
    path: /tmp/mnt-pnt
    state: unmounted

- name: Mount and bind a volume
  mount:
    path: /system/new_volume/boot
    src: /boot
    opts: bind
    state: mounted
    fstype: none
```
